import type { Metadata } from "next"

import { siteConfig } from "@/config/site"
import { Prose } from "@/components/docs/prose"

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms for using DevTools AI.",
}

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl px-4 py-16 sm:px-6 lg:px-8">
      <Prose>
        <h1 className="text-2xl font-bold tracking-tight">Terms of Service</h1>
        <p>Last updated 2026-07-17.</p>

        <h2>Open-source software</h2>
        <p>
          {siteConfig.name} is released under the{" "}
          <a
            href={`${siteConfig.links.github}/blob/main/LICENSE`}
            target="_blank"
            rel="noopener noreferrer"
          >
            MIT License
          </a>
          . It is provided &ldquo;as is&rdquo;, without warranty of any kind,
          express or implied, including but not limited to warranties of
          merchantability, fitness for a particular purpose, and
          noninfringement. See the license for the full text.
        </p>

        <h2>No guaranteed availability</h2>
        <p>
          This is an open-source project, not a commercial hosted service. Any
          publicly hosted instance may be unavailable, rate-limited, or taken
          down without notice. There is no service-level agreement.
        </p>

        <h2>Acceptable use</h2>
        <p>You agree not to use this application to:</p>
        <ul>
          <li>
            Submit content you don&rsquo;t have the right to share, or that is
            unlawful, infringing, or malicious
          </li>
          <li>
            Attempt to circumvent rate limits, the model allowlist, or other
            technical restrictions
          </li>
          <li>Abuse, overload, or disrupt any deployment of this app</li>
        </ul>

        <h2>Third-party services</h2>
        <p>
          Every tool response is generated by a third-party model accessed
          through OpenRouter. Your use of those models is also subject to{" "}
          <a
            href="https://openrouter.ai/terms"
            target="_blank"
            rel="noopener noreferrer"
          >
            OpenRouter&rsquo;s Terms of Service
          </a>{" "}
          and the terms of the underlying model provider. AI-generated output
          can be wrong — review it before relying on it, especially for code,
          security, or legal content.
        </p>

        <h2>Changes</h2>
        <p>
          These terms may change as the project evolves. Updates will be
          reflected on this page and noted in the{" "}
          <a href="/changelog">changelog</a>.
        </p>

        <h2>Contact</h2>
        <p>
          Questions about these terms can be sent through the{" "}
          <a href="/contact">Contact</a> page.
        </p>
      </Prose>
    </div>
  )
}
